### ISSUE TITLE
5 things

### ISSUE THREAD

**Issue by jameshyen** [NAnguiano/memescript#4]
1. What about the keywords very ("new"), much ("this"), and so on and so forth, do we need semantic action for that?
2. Our grammar for the Try-Catch and the Try-Catch-Finally does not actually catch an "error" object. The catch part was removed, so now there's just a body.
3. ~~What about the alert statement? We have console.log(), but not alert().~~ (Nicole fixed this.)
4. We need to add some sort of typing system to our language.
5. We should add a semicolon to the end of the While statement.

**Comment by NAnguiano** [comment]
I just fixed number 2.

For 1, we probably do need a semantic action for it. I'll look into adding that.
For 4, if we're doing that, then we're moving away from weak typing. I'm not sure the day an assignment is due is the best time to do that.
For 5, why? There isn't one at the end of if, for, or switch. Unless you mean at the end of one of the lines in a file?

**Comment by jameshyen** [comment]
Ok sure.

Ok sure.
Yes I added that as a log of things we should do in the future. Since from the meeting you and Claire had with Toal, you said that he said that: "we should at least be doing some form of typing" ("so that we can be doing more than we are doing").
It just seems ambiguous to me.

I'm not adding these things here for immediate resolution, it's just a log of ~~these~~ things we should do in the future. Like a punchlist, or a to-do list of issues. It's just a list of issues.

**Comment by NAnguiano** [comment]
Sounds good! We'll figure things out after the break.
